refactor: automated user status
Code-dig-ger/Backend pull request #25
Opened 2021-09-30 14:41 UTC by jyothiprakashpanaik

# Efficient Use of Codeforces API

Fixed the hardcoded to neat and clean code. Created a new function in the API file under the name user status and called them wherever required. 
Fixes #9 [Efficient Use of Codeforces API](https://github.com/Code-dig-ger/Backend/issues/9)

**New feature (non-breaking change which adds functionality)**

## How Has This Been Tested?

Worked with python [unittest](https://django-testing-docs.readthedocs.io/en/latest/basic_unittests.html) to verify my changes.
```python manage.py test``` 

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings

2021-09-30 17:03 UTC, ShivamSinghal1 requested changes
@jyothiprakashpanaik

2021-09-30 17:03 UTC, ShivamSinghal1 commented on codedigger/codeforces/api.py
> +def user_status(handle):
Add from and count param too. 
from | 1-based index of the first submission to return.
count | Number of returned submissions.

See API [user.status](https://codeforces.com/apiHelp/methods#user.status)

Example - 
```python 
user_status(handle, from = None, count = None) 
```

If from and count is given to this function use that too.

2021-09-30 17:03 UTC, ShivamSinghal1 commented on codedigger/codeforces/api.py
> +    return data['result']
Use validated response function to validate. This will remove all the above lines.
```python
return validated_response(response)
```

2021-09-30 17:03 UTC, ShivamSinghal1 commented on codedigger/contest/views.py
> +            except ValidationException as err:
Do Not use try-except block here. Function will automatically raise exception.

2021-09-30 17:05 UTC, ShivamSinghal1 requested changes

2021-09-30 17:05 UTC, ShivamSinghal1 commented on codedigger/problem/utils.py
>      for submission in data['result']:
Change data["result"] to data

2021-09-30 18:24 UTC, jyothiprakashpanaik commented on codedigger/contest/views.py
> +            except ValidationException as err:
But if we don't use try-except block, than how could we send HTTP response's

2021-10-01 03:42 UTC, ShivamSinghal1 commented on codedigger/contest/views.py
> +            except ValidationException as err:
```python 
raise ValidationException('err')
``` 
is same as
```python
return Response ( {
    'status' : 'FAILED', 
    'error'   : 'err' 
} )
```
See Exception File.

2021-10-01 07:22 UTC, jyothiprakashpanaik commented on codedigger/contest/views.py
> +            except ValidationException as err:
I think then in the except block we can replace it to
```python
try:
    # call the uset_status() function
except ValidationException as err:
    return err
```

or we have to remove the complete try-except bock directly call the function completely.
```python
data = user_status(handle=handle) 
# rest of the code goes here ...
```

2021-10-01 09:26 UTC, ShivamSinghal1 commented on codedigger/contest/views.py
> +            except ValidationException as err:
Yes, remove the complete try-except block directly call the function completely

2021-10-01 09:32 UTC, ShivamSinghal1 approved these changes
Good

2021-10-01 09:33 UTC, merged